### ISSUE TITLE
[DOCUMENTATION] Update single: The locale field is required.

### ISSUE THREAD

**Issue by phh** [BenjaminMedia/bonnier-php-sdk#51]
https://github.com/BenjaminMedia/bonnier-php-sdk/blob/master/trapp.md#update-single

Using the example code from update single gives an error message: The locale field is required.

I regards to that. Which fields would I need to update for every new revision?

**Comment by skipperbent** [comment]
I'm not sure actually, but I dont think you need to provide locale when updating, so that error sounds like the SDK is trying to do a save, instead of an update.

This might be helpful in regards to Trapp:
https://github.com/BenjaminMedia/app-wiki/blob/master/trapp.wiki/Home.md

Please check that you are using latest version of the SDK as I recently fixed some errors regarding save:
https://github.com/BenjaminMedia/bonnier-php-sdk/releases/tag/2.7.2

**Comment by skipperbent** [comment]
Please try to update to version 2.7.3 and see if it resolves the issue.

I found some bugs - and after the fix I was able to save, edit and delete without getting the "locale required" exception.

**Comment by phh** [comment]
Updated the SDK and the exception is gone.
