### ISSUE TITLE
[HELP] TRAPP delete not deleting

### ISSUE THREAD

**Issue by phh** [BenjaminMedia/bonnier-php-sdk#53]
I know it's not a part of the current documentation but it worked for the IndexSearch service.

Setting the service:

```
    $service = new \Bonnier\Trapp\ServiceTranslation($username, $secret);
    $service->setDevelopment(true);
```

Returns the row:

```
var_dump($service->getById( '56016d39c01443db5a8b4595')->getRow())
```

Trying to delete it:

```
$service->delete( '56016d39c01443db5a8b4595' );
```

Gives an Unhandled Exception:

```
Unhandled Exception

Message:

Method not allowed or bad request.
Location:

.../vendor/bonnier/php-sdk/src/Bonnier/IndexSearch/ServiceRestBase.php on line 68
```

From my point of view I'm thinking: Is it correct that TRAPP uses the ServiceRestBase from IndexSearch?

**Comment by skipperbent** [comment]
`From my point of view I'm thinking: Is it correct that TRAPP uses the ServiceRestBase from IndexSearch?`

Yeah, thats fine - that's because the api is structured similar to the index-search API. It has the same output for collections and uses the same basic authentication, so that should not cause the problem.

It sound like one of these errors:
- The SDK is posting to the wrong url.
- The SDK is posting using the wrong post-type (delete is the right one for METHOD_DELETE is the correct one for deleting an item in a Laravel ressource controller). 
- The delete method is not implemented in the TRAPP api.

I'll try to do some tests and i'll get back to you right away.

**Comment by skipperbent** [comment]
Please try to update to version 2.7.3 and see if it resolves the issue.

I found some bugs - and after the fix I was able to save, edit and delete without getting the "locale required" exception.

**Comment by phh** [comment]
Have just updated:

`"version": "2.7.3"`

Trying to delete:
`$service->delete( '5601679fc01443db5a8b4567' );`

Now gives:

`The locale field is required. The translate into field is required. The deadline field is required. The fields field is required. The title field is required.`

**Comment by skipperbent** [comment]
Ahh that's because i've just changed the behaviour of the SDK.

Try this instead

``` php
$item = $service->getById('5601679fc01443db5a8b4567');
$item->delete();
```

**Comment by phh** [comment]
A great! Will try that out. Would that be the same with the IndexSearch. Using getById instead of delete($id) ?

**Comment by skipperbent** [comment]
Yes, maybe I should update the release log to reflect the changes + the documentation. 

If you want - or find it easier, I can implement a method so you can delete by id as well, but the old way didn't really make sense to provide the id, when you've already fetched the item. :)

**Comment by phh** [comment]
I actually tryed getById before trying out $service->delete($id). To me I rather fetch the item and then delete. Either way I'm not going to do any work to the IS integration until you are done with your sprint :)

**Comment by phh** [comment]
Item deleting! Thank you!

**Comment by skipperbent** [comment]
You're right.. Cool - just let me know if you need any further assistance and thanks for the feedback..
